language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "AtomAwa"
  - git config user.email "1206192226@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_Token}${GH_REF}" master:website
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/AtomAwa/MyProject.git
